### ISSUE TITLE
Unforgeable TrustedTypes could be a problem

### ISSUE THREAD

**Issue by caridy** [salesforce/near-membrane#34]
When @jdalton was trying canary, he found some issues with TrustedTypes, specifically, the new global is unforgeable, forcing this library to add more offenders for the membrane.

Ref: https://w3c.github.io/webappsec-trusted-types/dist/spec/#trusted-types

Few questions arise:

1. why making TrustedTypes unforgeable? Does it really solve any issue?
2. if it remains unforgeable? how to deal with this via the membrane? do we need to replace its descriptors? or should we remap them?

**Comment by caridy** [comment]
@erights suggested reaching out to our friend @mikesamuel, so we can explain the details, and see if we can get to something here.

**Comment by mikesamuel** [comment]
How does unforgeability cause a problem?  Are you not unwrapping before things reach the DOM?

I forget the distinctions between the subtly different flavours of "global."  Is one preferable to others?

+@koto

**Comment by erights** [comment]
I am confused by the word "unforgeable". The way I use the terms, TrustedTypes must be unforgeable. From my recent conversation with Caridy, my understanding of the real issue, put in purely EcmaScript terms:

As I understand it, the TrustedTypes would add new non-configurable properties to the global object. If so, this is a problem. Instead, these must start configurable in all the normal ways: Both attribute `configurable: true` and actually deletable and reconfigurable/replaceable. They should also be effectively freezable, i.e., can be turned into a property that acts like a non-configurable, non-writable data property. A SES-like startup script may choose to do so, after such removal or replacement. It must be able to make this choice. However, because of the Window/WindowProxy split, even after the property is effectively make non-configurable/non-writable, it must still claim to be `configurable: true`.

This should be true for *all* new properties added to the global object by any host. I will be making a proposal along those lines.

**Comment by koto** [comment]
I'm not sure I follow for SES requirement, but in the platform the global object has [many](https://html.spec.whatwg.org/multipage/window-object.html#window) unforgeable properties, and their unforgeability is definitely not going away for security reasons.

**Comment by caridy** [comment]
Not that many @koto! We have to deal with those of course, no way to change them at this point IMHO, but the real question here is: should we continue adding unforgeable properties to the global? what is the reason for that to be unforgeable? We have discussed this in the SES meetings few times... making them non-configurable does not give you much, unless that it is pretty tied to the host behavior for some reasons.

Maybe we can go over the details in the next SES meetings or in the next TC39 meeting, we have many questions about the behavior of trusted types once the host is disconnected (e.g.: disconnected iframe with pending stack entries, or hard references from the opener for same domain iframes).

**Comment by erights** [comment]
From @caridy 's presentation at yesterday's SES mtg at https://www.youtube.com/watch?v=TaPot2OyXHU&list=PLzDw4TTug5O1jzKodRDp3qec8zl88oxGd there are only 6 browser host objects we cannot remove from the global. For all of these, we can bleach them, i.e., make them inoperative by
   * detaching the frame
   * deleting all builtin methods that understand those exotic objects, i.e., that operate on their internal slots.

The second bullet is only possible because these methods are only held onto by configurable properties.

My upcoming tc39 proposal will grandfather in these 6, together with the current behavior that allows us to bleach them.

Many details in that video. Worth watching!

**Comment by koto** [comment]
I might be completely off as I'm not dealing with proxies and membranes day to day, sorry for that. TT are tied to the host behavior IIUC - the instances of the types are required for some DOM sinks. Originally we defaulted to unforgeability to prevent modifying this security API, and especially spoofing the TT objects, replacing their inner values or return values from `trustedTypes.is*` functions. 

That said, those checks are now implemented in the browser engine, and I'm not sure if we lose anything of those properties by removing unforgeability from the IDL, but keeping API hardening in the polyfill code. Can you file a bug?

That said, TT are a CSP feature, so the restrictions placed upon the DOM (i.e. that the sinks accept TT objects only) in the main window do propagate to other iframes (e.g. `about:blank`). This property is crucial.

**Comment by erights** [comment]
Having the actual DOM accept only actual TTs is great! Indeed, it is necessary. Any environment that replaces the TTs and preserves apparent browser behavior would also have to virtualize the dom so that the virtual dom recognizes the replacement TTs.

**Comment by caridy** [comment]
@mikesamuel @koto any update about making Trusted Types forgeable?

**Comment by caridy** [comment]
@mikesamuel I haven't seen any update on the trusted types repo, any feedback on this?
