### ISSUE TITLE
[Question] What does VirtualEnvironment.link do?

### ISSUE THREAD

**Issue by Jack-Works** [salesforce/near-membrane#378]
I see the following usage in the source code:

```js
env.link('window', 'document');
env.link('document');
env.link('__proto__', '__proto__', '__proto__');
ve.link('globalThis');
```

What did it do?

**Comment by jdalton** [comment]
https://github.com/salesforce/near-membrane/blob/85957ac7b4b2fa7b0149e350194c39adfbfbf327/packages/near-membrane-dom/src/browser-realm.ts#L119-L133

☝️ `env.link()` as seen in source here:
https://github.com/salesforce/near-membrane/blob/85957ac7b4b2fa7b0149e350194c39adfbfbf327/packages/near-membrane-base/src/environment.ts#L278-L288

Wires up pointers

https://github.com/salesforce/near-membrane/blob/85957ac7b4b2fa7b0149e350194c39adfbfbf327/packages/near-membrane-base/src/membrane.ts#L3529-L3542

and

https://github.com/salesforce/near-membrane/blob/85957ac7b4b2fa7b0149e350194c39adfbfbf327/packages/near-membrane-base/src/membrane.ts#L3559-L3571

So that `env.evaluate('document')` will return the `document` reference of the blue realm directly without a proxy wrap to the red realm.
```js
env.evaluate('document') === document // true
```
and within the red realm the `document` will be that of the red realm and not a proxy of the blue. This is done for things like reflective intrinsics and non-configurable properties (of the detached iframe in this case). We later remap properties on things like red realm `document` with property descriptors to return proxied values.
