### ISSUE TITLE
`Symbol.toStringTag` checks for proxies

### ISSUE THREAD

**Issue by jdalton** [salesforce/near-membrane#6]
This is just a todo to remember to address the `Symbol.toStringTag` check for proxies. The issue is proxies will `Object.prototype.toString.call(proxied)` as either an `[object Object]` or a `[object Function]` but not as anything else. In those cases the `proxied` value will need to project a `Symbol.toStringTag` value to cover it.

For reference you can see [this](https://github.com/standard-things/esm/blob/868a9029e34ba3f57498736642b879d1671f499e/src/util/proxy-exports.js#L210-L215) and [this](https://github.com/standard-things/esm/blob/868a9029e34ba3f57498736642b879d1671f499e/src/util/proxy-exports.js#L278-L292).

**Comment by caridy** [comment]
@jdalton can you take this one?

**Comment by caridy** [comment]
Additionally, this issue should also hide the function body when stringifying them across the membrane to produce the equivalent to native functions. The sandbox should never get access to the source of a function from the outer realm because the source might contain information (secrets) that they might be able to scrape out of the string value.
